// <auto-generated />
using CircuitManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CircuitManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250906012844_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("CircuitElementComponent", b =>
                {
                    b.Property<int>("CircuitElementsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CircuitElementsId", "ComponentListId");

                    b.HasIndex("ComponentListId");

                    b.ToTable("CircuitElementComponents", (string)null);
                });

            modelBuilder.Entity("CircuitManager.Models.CircuitElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextCircuitElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NextCircuitElementId");

                    b.ToTable("CircuitElements");
                });

            modelBuilder.Entity("CircuitManager.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Shortcut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("CircuitElementComponent", b =>
                {
                    b.HasOne("CircuitManager.Models.CircuitElement", null)
                        .WithMany()
                        .HasForeignKey("CircuitElementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CircuitManager.Models.Component", null)
                        .WithMany()
                        .HasForeignKey("ComponentListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CircuitManager.Models.CircuitElement", b =>
                {
                    b.HasOne("CircuitManager.Models.CircuitElement", "NextCircuitElement")
                        .WithMany()
                        .HasForeignKey("NextCircuitElementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NextCircuitElement");
                });
#pragma warning restore 612, 618
        }
    }
}
